/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ave;

import java.util.LinkedList;

/**
 *
 * @author rzl
 */
public class pop extends javax.swing.JFrame {

    /**
     * Creates new form pop
     */
    LinkedList<Aev> sl = new LinkedList<>();
    
    public pop() {
        initComponents();
    }
    
    void showSoal() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilgan = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_soal = new javax.swing.JTable();
        pil_a = new javax.swing.JTextField();
        pil_b = new javax.swing.JTextField();
        pil_c = new javax.swing.JTextField();
        pil_d = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        j_desk = new javax.swing.JTextArea();
        btn_soal_new = new javax.swing.JButton();
        btn_soal_save = new javax.swing.JButton();
        btn_soal_update = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        kc_a = new javax.swing.JRadioButton();
        kc_b = new javax.swing.JRadioButton();
        kc_c = new javax.swing.JRadioButton();
        kc_d = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_soal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Soal", "pilihan A", "pilihan B", "pilihan C", "pilhan D", "Kunci Jawaban"
            }
        ));
        jScrollPane1.setViewportView(tbl_soal);

        pil_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil_cActionPerformed(evt);
            }
        });

        j_desk.setColumns(20);
        j_desk.setRows(5);
        jScrollPane2.setViewportView(j_desk);

        btn_soal_new.setText("New");

        btn_soal_save.setText("Save");

        btn_soal_update.setText("Update");

        jButton4.setText("?");

        pilgan.add(kc_a);

        pilgan.add(kc_b);

        pilgan.add(kc_c);

        pilgan.add(kc_d);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_soal_new, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_soal_save, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_soal_update, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pil_d, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(pil_b)
                                    .addComponent(pil_a)
                                    .addComponent(pil_c))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kc_a)
                                        .addComponent(kc_b, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(kc_c))
                                    .addComponent(kc_d, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pil_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kc_a))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pil_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kc_b))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pil_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kc_c))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pil_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kc_d)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_soal_new)
                    .addComponent(btn_soal_save)
                    .addComponent(btn_soal_update)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pil_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pil_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_soal_new;
    private javax.swing.JButton btn_soal_save;
    private javax.swing.JButton btn_soal_update;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea j_desk;
    private javax.swing.JRadioButton kc_a;
    private javax.swing.JRadioButton kc_b;
    private javax.swing.JRadioButton kc_c;
    private javax.swing.JRadioButton kc_d;
    private javax.swing.JTextField pil_a;
    private javax.swing.JTextField pil_b;
    private javax.swing.JTextField pil_c;
    private javax.swing.JTextField pil_d;
    private javax.swing.ButtonGroup pilgan;
    private javax.swing.JTable tbl_soal;
    // End of variables declaration//GEN-END:variables

    private static class Aev {
        
        private int id_soal;
        private String desk;
        private String jwbn_a,jwbn_b,jwbn_c,jwbn_d;
        private String kunci_jwbn;

        public Aev() {
            
        }
        
        public Aev(int id_soal1, String desk1, String jwbn_a1, String jwbn_b1, String jwbn_c1, String jwbn_d1, String kunci_jwbn1) {
            this.id_soal = id_soal1;
            this.desk = desk1;
            this.jwbn_a = jwbn_a1;
            this.jwbn_b = jwbn_b1;
            this.jwbn_c = jwbn_c1;
            this.jwbn_d = jwbn_d1;
            this.kunci_jwbn = kunci_jwbn1;
        }

        /**
         * @return the id_soal
         */
        public int getId_soal() {
            return id_soal;
        }

        /**
         * @param id_soal the id_soal to set
         */
        public void setId_soal(int id_soal) {
            this.id_soal = id_soal;
        }

        /**
         * @return the desk
         */
        public String getDesk() {
            return desk;
        }

        /**
         * @param desk the desk to set
         */
        public void setDesk(String desk) {
            this.desk = desk;
        }

        /**
         * @return the jwbn_a
         */
        public String getJwbn_a() {
            return jwbn_a;
        }

        /**
         * @param jwbn_a the jwbn_a to set
         */
        public void setJwbn_a(String jwbn_a) {
            this.jwbn_a = jwbn_a;
        }

        /**
         * @return the jwbn_b
         */
        public String getJwbn_b() {
            return jwbn_b;
        }

        /**
         * @param jwbn_b the jwbn_b to set
         */
        public void setJwbn_b(String jwbn_b) {
            this.jwbn_b = jwbn_b;
        }

        /**
         * @return the jwbn_c
         */
        public String getJwbn_c() {
            return jwbn_c;
        }

        /**
         * @param jwbn_c the jwbn_c to set
         */
        public void setJwbn_c(String jwbn_c) {
            this.jwbn_c = jwbn_c;
        }

        /**
         * @return the jwbn_d
         */
        public String getJwbn_d() {
            return jwbn_d;
        }

        /**
         * @param jwbn_d the jwbn_d to set
         */
        public void setJwbn_d(String jwbn_d) {
            this.jwbn_d = jwbn_d;
        }

        /**
         * @return the kunci_jwbn
         */
        public String getKunci_jwbn() {
            return kunci_jwbn;
        }

        /**
         * @param kunci_jwbn the kunci_jwbn to set
         */
        public void setKunci_jwbn(String kunci_jwbn) {
            this.kunci_jwbn = kunci_jwbn;
        }
        
        
    }
}
