/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ave;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.*;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rzl
 */
public class testing extends javax.swing.JFrame {

    /**
     * Creates new form testing
     */
    LinkedList<Ave> mk = new LinkedList<>();
    LinkedList<Eva> pb = new LinkedList<>();
    private int index_mk = 0;
    
    Connection con;
    Statement state;
    ResultSet set;
    
    public testing() {
        initComponents();
        
        String serverName = "localhost";
        String myDatabase = "ave";
        String url = "jdbc:mysql://" + serverName + "/" + myDatabase; //a JDBC url
        String uname = "root";
        String pass = "";
        String driverName = "org.gjt.mm.mysql.Driver"; //JDBC
        
        try {
            Class.forName(driverName);
            con = DriverManager.getConnection(url, uname, pass);
            System.out.println("Connected");
            
            String query = "SELECT * FROM mata_kuliah";
        
            state = con.createStatement();
            set = state.executeQuery(query);
            
            while (set.next()) {                
                mk.add(new Ave(
                        set.getInt(1),
                        set.getString(2)));
            }
            
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Not Connected");
        }
        
        showMatkul();
        showPokba(tbl_matkul);
    }
    
    void showMatkul() {
        for (int i = 0; i < mk.size(); i++) {
            ((DefaultTableModel)this.tbl_matkul.getModel()).setRowCount(i+1);
            tbl_matkul.setValueAt(mk.get(i).getMatkul(), i, 0);
        }
    }
    
    void showTable() {
        
        for (int i = 0; i < pb.size(); i++) {
            ((DefaultTableModel)this.tbl_pokba.getModel()).setRowCount(i+1);
            tbl_pokba.setValueAt(pb.get(i).getPokba(), i, 0);
        }
    }
    
    void showPokba(final JTable tabel) {
        
        
        MouseListener selCell;
        selCell = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tabel.rowAtPoint(e.getPoint());
                int col = tabel.columnAtPoint(e.getPoint());
                String value = tabel.getValueAt(row, col).toString();
                
                String query = "SELECT * FROM pokok_bahasan JOIN mata_kuliah WHERE mata_kuliah.id=pokok_bahasan.id_matkul AND mata_kuliah.matkul='"+value+"'";
                try {
                    state = con.createStatement();
                    set = state.executeQuery(query);
                    
                    while(set.next()) {
                        pb.add(new Eva(
                                set.getInt(1),
                                set.getString(2)
                        ));
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(testing.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                showTable();
                pb.clear();
            }
        };
        tabel.addMouseListener(selCell);
    }
    
    void viewSoal() {
        new pop().setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_matkul = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        j_new = new javax.swing.JButton();
        j_save = new javax.swing.JButton();
        j_update = new javax.swing.JButton();
        j_view = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pokba = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_matkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Matkul"
            }
        ));
        tbl_matkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_matkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_matkul);

        j_new.setText("New");

        j_save.setText("Save");

        j_update.setText("update");
        j_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_updateActionPerformed(evt);
            }
        });

        j_view.setText("view");
        j_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_viewActionPerformed(evt);
            }
        });

        tbl_pokba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pokba"
            }
        ));
        jScrollPane2.setViewportView(tbl_pokba);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j_update, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j_new))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(j_view, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j_save))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_new)
                            .addComponent(j_update))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_save)
                            .addComponent(j_view)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_updateActionPerformed
        
    }//GEN-LAST:event_j_updateActionPerformed

    private void tbl_matkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_matkulMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_matkulMouseClicked

    private void j_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_viewActionPerformed
        // TODO add your handling code here:
        viewSoal();
    }//GEN-LAST:event_j_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton j_new;
    private javax.swing.JButton j_save;
    private javax.swing.JButton j_update;
    private javax.swing.JButton j_view;
    private javax.swing.JTable tbl_matkul;
    private javax.swing.JTable tbl_pokba;
    // End of variables declaration//GEN-END:variables
}
